# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "aez", # <extract_ae_zone>
  "location", # <extract_data_drill>
  "location", # <extract_patched_point>
  "owner", # <extract_patched_point>
  "station_code", # <extract_patched_point>
  "ind", # <extract_patched_point>
  NULL
))
